-- MySQL Script generated by MySQL Workbench
-- Thu Oct 17 09:03:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`partners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`partners` (
  `partner_id` INT NOT NULL,
  `partner_name` VARCHAR(45) NOT NULL,
  `partner_loc` VARCHAR(45) NOT NULL,
  `partnerscol` VARCHAR(45) NOT NULL,
  `order_order_id` INT NOT NULL,
  PRIMARY KEY (`partner_id`),
  INDEX `fk_partners_order1_idx` (`order_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_partners_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `mydb`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`restaurant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`restaurant` (
  `resto_id` INT NOT NULL,
  `resto_name` VARCHAR(45) NOT NULL,
  `resto_found_date` VARCHAR(45) NOT NULL,
  `resto_owner` VARCHAR(45) NOT NULL,
  `partners_partner_id` INT NOT NULL,
  PRIMARY KEY (`resto_id`),
  INDEX `fk_restaurant_partners_idx` (`partners_partner_id` ASC) VISIBLE,
  CONSTRAINT `fk_restaurant_partners`
    FOREIGN KEY (`partners_partner_id`)
    REFERENCES `mydb`.`partners` (`partner_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `customer_id` INT NOT NULL,
  `cust_lname` VARCHAR(45) NOT NULL,
  `cust_fname` VARCHAR(45) NOT NULL,
  `cust_initial` VARCHAR(45) NOT NULL,
  `cust_add` VARCHAR(45) NOT NULL,
  `cust_city` VARCHAR(45) NOT NULL,
  `cust_postcode` VARCHAR(45) NOT NULL,
  `cust_phone` VARCHAR(45) NOT NULL,
  `cust_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`food`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`food` (
  `food_id` INT NOT NULL,
  `food_name` VARCHAR(45) NOT NULL,
  `food_price` VARCHAR(45) NOT NULL,
  `food_type` VARCHAR(45) NOT NULL,
  `customer_customer_id` INT NOT NULL,
  PRIMARY KEY (`food_id`),
  INDEX `fk_food_customer1_idx` (`customer_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_food_customer1`
    FOREIGN KEY (`customer_customer_id`)
    REFERENCES `mydb`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `order_id` INT NOT NULL,
  `order_date` VARCHAR(45) NOT NULL,
  `order_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`partners`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`partners` (
  `partner_id` INT NOT NULL,
  `partner_name` VARCHAR(45) NOT NULL,
  `partner_loc` VARCHAR(45) NOT NULL,
  `partnerscol` VARCHAR(45) NOT NULL,
  `order_order_id` INT NOT NULL,
  PRIMARY KEY (`partner_id`),
  INDEX `fk_partners_order1_idx` (`order_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_partners_order1`
    FOREIGN KEY (`order_order_id`)
    REFERENCES `mydb`.`order` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
